# Generated by Django 5.0.3 on 2024-03-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='locatoin',
            new_name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
