version: "3"

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/bar
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - bar-api
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.local

  postgres-db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
    restart: "on-failure"
    networks:
      - bar-api

networks:
  bar-api:
    driver: bridge

volumes:
  postgres_data:
