version: '3.4'

services:
  bar:
    image: bar
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
      - 5678:5678
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_HOST: ${PG_HOST}
    restart: "on-failure"
    networks:
      - bar-api

networks:
  bar-api:
    driver: bridge

volumes:
  db_data: