version: '3.4'

services:
  web:
    image: bar
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    volumes:
      - .:/bar  # Maps the current directory (bar/) to /bar in the container
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bar-api
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_HOST: ${PG_HOST}
    restart: "on-failure"
    networks:
      - bar-api

networks:
  bar-api:
    driver: bridge

volumes:
  db_data:
  
  