# Generated by Django 5.0.3 on 2024-05-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='ordered', max_length=10),
        ),
    ]
