# Generated by Django 5.0.3 on 2024-04-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_barinventoryitem_date_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='date_purchased',
            field=models.DateField(),
        ),
    ]
