# Generated by Django 5.0.3 on 2024-05-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='delivered',
        ),
    ]
