# Generated by Django 5.0.3 on 2024-04-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_purchaseitem_date_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
